### ISSUE TITLE
"pythonic_params" causes strange behavior with incorrectly-cased query parameters

### ISSUE THREAD

**Issue by rlmv** [zalando/connexion#1183]
### Description

I have an app that sets `pythonic_params=True`. The app has an endpoint with a camel case query parameter (eg `orderBy=ascending`). If a request erroneously provides an `order_by=ascending` query parameter a mangled value is passed to the view function.

### Expected behaviour

The snake case query parameter is ignored, or correctly deserialized. 

### Actual behaviour

The route is passed `order_by = "['ascending']"`.

#### openapi.yml

```
openapi: '3.0.0'
info:
  title: 'pythonic_params bug'
  version: '1.0.0'

paths:
  /query:
    get:
      operationId: "app.test_query"
      parameters:
        - name: orderBy
          in: query
          required: false
          schema:
            type: string
      responses:
        default:
          description: 'A test'

```

#### app.py

```
from typing import Optional

import connexion


def test_query(order_by: Optional[str] = None):
    return {'order_by': str(order_by), 'type': str(type(order_by))}


if __name__ == "__main__":
    app = connexion.App(__name__)
    app.add_api('openapi.yml', pythonic_params=True)
    app.run(port=8000)

```

#### Request
```
curl "localhost:8000/v1/query?order_by=ascending"
```

#### Response

```
{
  "order_by": "['ascending']",
  "type": "<class 'str'>"
}
```

### Additional info:

Output of the commands:

- `python --version` - Python 3.7.4 
- `pip show connexion | grep "^Version\:"` - Version: 2.6.0
- `pip freeze`

```
certifi==2019.11.28
chardet==3.0.4
click==7.1.1
clickclick==1.2.2
connexion==2.6.0
Flask==1.1.1
idna==2.9
inflection==0.3.1
itsdangerous==1.1.0
Jinja2==2.11.1
jsonschema==2.6.0
MarkupSafe==1.1.1
openapi-spec-validator==0.2.8
PyYAML==5.3.1
requests==2.23.0
six==1.14.0
urllib3==1.25.8
Werkzeug==1.0.0
```

**Comment by heliomartins** [comment]
Hi there,

Firstly, apologies if this is the wrong thread or wrong way to contact regarding my question/problem.

I've been defining my schema properties in the `yaml` file with cameCase, example.

``` 
areaSize:
     type: number
      description: "Square meters of the land."
      minimum: 0
      maximum: 100000
      example: 256.85
```

Previously, using `pythonic_params=True` would automatically convert all the `REQUESTS` from `camelCase` to `snake_case`. Now, I need to use inflection. Currently using the suggested [example](https://marshmallow.readthedocs.io/en/latest/examples.html#inflection-camel-casing-keys
). If I do *not* do it, I'm going to get 500 Internal Server Errors, saying that areaSize is not defined. This is because all my schemas in python are defined with snake_case.

Is there something that I'm missing here? Is connexion not meant to support the `openapi.yaml` file with properties in camelCase?

That's my current server configuration.

**Server**
```
    def __init__(self):
        options = {'swagger_path': swagger_ui_3_path}
        self.app = connexion.App(__name__, specification_dir=OPENAPI_PATH + "/", options=options)
        self.app.add_api(self._build_openapi_file(), pythonic_params=True)
        self.register_errorhandlers()
        CORS(self.app.app, resources={r"/*": {"origins": "*"}})
```

Thank you!

**Comment by RobbeSneyders** [comment]
Thanks @rlmv, can indeed reproduce.

@heliomartins if you still need help, please open a separate issue with minimal reproducible example.
