### ISSUE TITLE
Copyright infringement in utils.py

### ISSUE THREAD

**Issue by MalcolmSmithUK** [zalando/connexion#1199]
### Description

A Black Duck scan has highlighted a copyright infringement on https://github.com/zalando/connexion/blame/master/connexion/utils.py#L65.  

### Expected behaviour

The code is no longer a copyright infringement.

### Actual behaviour

The code is a copyright infringement.

### Steps to reproduce

... run another Black Duck scan?

### Additional info:

None

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by hjacobs** [comment]
I get it. It's April Fools' Day.

**Comment by MalcolmSmithUK** [comment]
No, really.  Black Duck highlighted this infringement - is it will any other organisation who goes through a due diligence process.  This is no an April Fools.

**Comment by hjacobs** [comment]
Did it highlight the comment? I mean the code is really just on line and in no way can be copyrighted.

Can you add a screenshot of the Black Duck finding?

**Comment by antonyedwards** [comment]
Hi ... I'm part of Malcolm's team and have been reviewing the BlackDuck scan. Yes, I was really hoping it was a joke too, but no, they are serious. Just to show you exactly how it was flagged ...

This is how it was shown on the summary view:
![image](https://user-images.githubusercontent.com/2156250/78147944-1e107700-742c-11ea-9037-dedebea605cf.png)

And then in the details tab it was shown as this:
![image](https://user-images.githubusercontent.com/2156250/78148067-4bf5bb80-742c-11ea-94a4-a3bd864ab4e2.png)

So basically it's saying that on line 65 of utils.py it's detected some unlicensed code.

Obviously we don't know how BlackDuck really works, but from what it's found I think it is mainly looking at headers and comments and looking for anything that suggests cut-and-paste code. I spoke to a lawyer about it who said that you could argue that one line of code is an "excerpt" under copyright law. Also that if you had anything from the author saying you could use this that'd probably be fine. But at the moment anything showing as Red in BlackDuck is of course making legal-types worried.

Apologies since this feels so trivial, but really would appreciate any support that prevents us having to do some kind of patching. Thanks!
