### ISSUE TITLE
How to use created global objects in the app

### ISSUE THREAD

**Issue by smolendawid** [zalando/connexion#1236]
### Description

I have my function `predict()` that should use a global object classifier but I don't know how to pass it to the app. 

```
def predict():
    return classifier.predict()


logging.basicConfig(level=logging.INFO)
app = connexion.FlaskApp(__name__, port=5000, specification_dir='swagger/')
app.add_api('swagger.yaml')


if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='')
    parser.add_argument('--model', required=True, help='path to the model')
    args = parser.parse_args()

    classifier = Classifier(path=args.model)
    app.run()
```

### Expected behaviour

I'd like to be able to use my object classifier

### Actual behaviour

> NameError: name 'classifier' is not defined

I think there's some simple solution but I can't figure it out, I'd love to get some tip

**Comment by Ruwann** [comment]
It's because connexion imports your function based on the `operationId` during app startup. However, at that time, `__name__ != '__main__'`. You can easily see this by adding `print(__name__)`  at the top of your code.
If you create the classifier outside the `if __name__ == '__main__':` block, it should work as expected.
