### ISSUE TITLE
Version `>=2.7.0` results in `2018.0.dev1`

### ISSUE THREAD

**Issue by gaykg** [zalando/connexion#1240]
### Description
When specifying connexion version `>=2.7.0` version `2018.0.dev1` is imported

### Expected behaviour
Version 2.7.0 or greater is imported

### Actual behaviour
Version `2018.0.dev1` is imported

### Steps to reproduce
Create a Pipfile and specify `connexion = ">=2.7.0"`
Run `pip install`

### Additional info:
Version `2018.0.dev1` is imported due to https://pypi.org/project/connexion/#history

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by jmcs** [comment]
`2018.0.dev1` is marked as a pre-release in pypi:
![image](https://user-images.githubusercontent.com/3719966/82292601-7c2cf580-99ab-11ea-9e03-b4239792424f.png)

If pip is installing it without `--pre` then I would say it's a bug in either pypi or pip.

To solve the issue immediately, and since the pre-release is outdated, I deleted it.
