### ISSUE TITLE
Any plans to provide fastapi backend support instead of flask?

### ISSUE THREAD

**Issue by deepakiim** [zalando/connexion#1264]
https://fastapi.tiangolo.com/
https://towardsdatascience.com/why-we-switched-from-flask-to-fastapi-for-production-machine-learning-765aab9b3679

**Comment by apatap** [comment]
Connexion supports [aiohttp](https://docs.aiohttp.org/en/stable/) in case you are looking for an async backend.

see e.g. https://github.com/zalando/connexion/tree/master/examples/openapi3/helloworld_aiohttp

In my understanding fastapi is not API First, since it is generating the OpenAPI specification. So I am not sure, if that would be a good fit as a backend for an API First framework like connexion.

**Comment by RobbeSneyders** [comment]
FastAPI provides the 'reversed' behavior of Connexion: it generates an OpenAPI spec from python code. See #380 for support for other frameworks in general.
