### ISSUE TITLE
How can I return 200 status on root instead of 404?

### ISSUE THREAD

**Issue by smolendawid** [zalando/connexion#1338]
Is it possible to return status 200 by default on the root instead of 404?

```
openapi: "3.0.0"
info:
  title: Title
servers:
  - url: http://localhost:5000/

paths:
  /:
    post:
      summary: Health check
      responses:
        '200':
          description: Server on

```
the above code returns the error "Empty function" due to empty "/" line.

**Comment by eanunez** [comment]
It is actually, due to a missing operation function. You have to add `operationId: <PathtoFunction>`
Let's say, your function at `views/index.py` will be,
```
def index():
      return 'Server on', 200
```

at .yml, you will end up having, 
```
openapi: "3.0.0"
info:
  title: Title
servers:
  - url: http://localhost:5000/

paths:
  /:
    get:
      summary: Health check
      operationId: views.index.index
      responses:
        '200':
          description: Server on
```
Notice that the method is changed to `get` instead of `post`, otherwise it will throw an error. I think it would make sense to have get here. 
Also don't forget to add the api at the app level. 

Hope this helps.

**Comment by smolendawid** [comment]
Thanks a lot, it solves the problem!
