### ISSUE TITLE
Support jsonschema >= 4.0.0

### ISSUE THREAD

**Issue by kruegener** [zalando/connexion#1430]
### Description

connexion uses the `_util` part of `jsonschema` package. There was a breaking change in the latest release 4.0 release of `jsonschema` removing the `types_msg` function.
Removal commit: https://github.com/Julian/jsonschema/commit/00031cb043763842266877923552e40f0c8f36b5

https://github.com/zalando/connexion/blob/main/connexion/json_schema.py#L64 uses the removed function.

### Expected behaviour

Not use missing private function.

### Actual behaviour

Uses missing private function. 

### Steps to reproduce

Install `jsonschema` with version 4.0 and up.

### Additional info:

Output of the commands:

- `python --version`: 3.6.10
- `pip show connexion | grep "^Version\:"`: 2.7.0

**Comment by kruegener** [comment]
I see the requirements of connexion have been changed with 2.8/2.9 to require `jsonschema<4`, solving this issue.
Are there any plans to support versions 4 and above?

**Comment by RobbeSneyders** [comment]
Thanks for the report @kruegener. This should indeed be fixed since version 2.8.

The reason to add the upper bound was exactly to prevent breaking changes in dependencies like this. Now that jsonschema 4 is out, we should fix and test the integration, and then increase the upper limit to the next major version.

I'll update this issue to reflect this.

**Comment by alex-zywicki** [comment]
Is there any progress on this? I'm experiencing this issue currently and have other non connexion related dependencies that require jsonschema >= 4.0.0 preventing me from using jsonschema < 4.0.0

**Comment by ewalshmndt** [comment]
With the release of openapi-schema-validator==0.2.0, I've got connexion conflicting with its own dependencies:
```
There are incompatible versions in the resolved dependencies:
  jsonschema (from openapi-spec-validator==0.3.1->connexion2==2.10.0->-r /tmp/pipenvf3jugp0grequirements/pipenv-p7f7j2ul-constraints.txt (line 9))
  jsonschema<4,>=2.5.1 (from connexion2==2.10.0->-r /tmp/pipenvf3jugp0grequirements/pipenv-p7f7j2ul-constraints.txt (line 9))
  jsonschema<5.0.0,>=4.0.0 (from openapi-schema-validator==0.2.0->openapi-spec-validator==0.3.1->connexion2==2.10.0->-r /tmp/pipenvf3jugp0grequirements/pipenv-p7f7j2ul-constraints.txt (line 9))
```

**Comment by jonrkarr** [comment]
I temporarily worked around the issue discussed by @alex-zywicki and @ewalshmndt by adding an additional constraint (e.g., `openapi-schema-validator < 0.2`).

**Comment by jonrkarr** [comment]
The current version of connexion can be used with openapi-schema-validator <= 0.1.6 because those versions of openapi-schema-validator have compatible version requirements for jsonschema. However, in my experience, pip isn't able to find this version of openapi-schema-validator, unless I add the add the additional requirement `openapi-schema-validator < 0.2`. Adding this additional requirement seems to help pip find this solution to the requirement for jsonschema. In principle, this shouldn't be needed, but pip doesn't appear to fully consider older versions of packages as potential solutions to the requirements.
