### ISSUE TITLE
Validation of Response code with the Swagger specifications

### ISSUE THREAD

**Issue by tanaysoni** [zalando/connexion#300]
Is there a way to perform validation of status code of responses? I've set `validate_responses` to True, but still any response code not defined in the Swagger is passed without an error.

**Comment by rafaelcaricio** [comment]
Short answer: No.

Long answer: We do not provide a way to validate status code of responses. We do that because developers using Connexion would need to define all response codes that their expect the application to possibly return ever, unless Connexion would throw an error. 

That behavior could be confusing. If not defined a response code of error (like 500) Connexion would return an different error saying that 500 is not defined in the API spec. That said, the developers would need to probably add to all endpoints of the API spec a few basic response codes that are not really important to the understand of their APIs. We would probably see 404, 500, 503 in all endpoints plus the success cases like 200, 201 etc.

If you see a value on that kind of validation you can send a PR to Connexion to add this kind of strict validation. We would consider accepting if it is implemented as an optional configuration.
