### ISSUE TITLE
type hints

### ISSUE THREAD

**Issue by twosigmajab** [zalando/connexion#716]
I'm new to Connexion. It looks like the source code does not currently leverage type hints or other ahead-of-time / static analysis correctness checks, is that right?

To fully leverage the power of API-first development, where implementations can be verified *before runtime* to be conformant to the interfaces declared in specifications, would it be valuable to add type hints to Connexion, and document how to use them to verify correctness ahead of runtime?

**Comment by jmcs** [comment]
> does not currently leverage type hints
In the very very first iterations Connexion had type hints, we removed them to support Python 2.7.

This is mostly not an issue because we have a very high test coverage, both in terms of code coverage (100%) and case coverage.

> other ahead-of-time / static analysis correctness checks

We use flake8.

> To fully leverage the power of API-first development, where implementations can be verified before runtime to be conformant to the interfaces declared in specifications, would it be valuable to add type hints to Connexion, and document how to use them to verify correctness ahead of runtime?

Type hints are not necessary, and they are definitely not sufficient, to verify correctness ahead of runtime.
For most real world cases verifying correctness ahead of runtime is not necessary, and, due to the necessary effort and constraints, not even desirable. But it can be approximated with a combination of other techniques - unit tests, integration tests, static checking, etc.

That said I hope to add at least some type hints to Connexion once we drop support for Python 2.7, since it will improve our static checks and document some of our assumptions.
