### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by elezar** [zalando/connexion#73]
When specifying {{https}} as the scheme in the API YAML file, all the URIs in the Swagger UI that is served are HTTPS endpoints. The problem is that the default server that is running is a "normal" HTTP server. This means that the Swagger UI cannot be used to play with the API.

What is the correct way to start a HTTPS server using connexion?

**Comment by cansik** [comment]
The default server of connexion is the werkzeug server which is used by flask. So if you want to provide an https server there are several ways to go. One way is described by flask [here](http://flask.pocoo.org/snippets/111/) and looks like this:

```python
from OpenSSL import SSL
context = SSL.Context(SSL.SSLv23_METHOD)
context.use_privatekey_file('yourserver.key')
context.use_certificate_file('yourserver.crt')

app.run(host='127.0.0.1',port='12344', 
        debug = False/True, ssl_context=context)
```

But there you will encounter the problem that connexion doesn't provide a `ssl_context` parameter at the moment. This is because flask doesn't either, but it uses `**kwargs` to send the parameters to the underlying werkzeug server.

I'm currently working on a pull-request to provide **kwargs options for werkzeug through connexion. Check it out here: #72

**Comment by elezar** [comment]
Yes, I saw the comments related to PR #72, thanks. There is still some time before I have to roll things out on this side, so I can wait for your changes. Let me know if there is anything that I should have a look at from this side.
