### ISSUE TITLE
Provide my swagger-ui distribution

### ISSUE THREAD

**Issue by vanoise** [zalando/connexion#792]
### Description
I installed the latest version of swagger-ui-dist with npm.
As explained in the documentation, I have specified the following option:

```
options = {'swagger_path': ‘~/node_modules/swagger-ui-dist'}
app = connexion.App(__name__, options=options)
```

The documentation also says that I should put a `index.j2` in a directory 
named `swagger_ui`. I have created this directory inside the directory
containing my python files and my swagger yaml interface description
file but I am still having the following error (in the Terminal) when trying to display
the UI with my browser:

### Actual behaviour

`jinja2.exceptions.TemplateNotFound: index.j2`

Could you tell me where I should put the `index.j2` file and what should be the
exact contents of this file ?
Thanks !

**Comment by dtkav** [comment]
Hey @vanoise - did you find the [swagger-ui-console](https://github.com/zalando/connexion/blob/master/README.rst#the-swagger-ui-console) section in the readme? 

You can also have a look at:
https://github.com/dtkav/swagger_ui_bundle/blob/master/swagger_ui_bundle/vendor/swagger-ui-3.17.1/index.j2#L44:L45
The important part is really just passing the default `openapi_spec_url`.
If you don't care about this, you can simply rename your file from `.html` to `.j2`.

The connexion project moved to using swagger-ui-bundle instead of vendoring swagger-ui directly.
If you'd like you can issue a ticket against that repo to bump the version.

**Comment by lsorber** [comment]
`swagger_ui_bundle` hasn't been updated for 6 months. Issue that requests a bump to the latest version: https://github.com/dtkav/swagger_ui_bundle/issues/2.

**Comment by dtkav** [comment]
swagger_ui_bundle has been update to 3.20.5

I've also updated the link above to an example jinja2 file: https://github.com/dtkav/swagger_ui_bundle/blob/383b1b6d1ed11a590cf9a8d66f3e961fc3372ee3/swagger_ui_bundle/vendor/swagger-ui-3.20.5/index.j2
